//
//  ContentView.swift
//  AssignmentOne
//
//  Created by Steele Cooke on 19/3/2023.
//

import SwiftUI

/// The main application view that displays a checklist.
///
/// `ContentView` is responsible for displaying the `CheckListView` with the associated list items.
/// It initializes the `list` and `listName` states and passes them to the `CheckListView`.
/// - Variables:
///     - list: [ListItem] - An array of `ListItem` objects representing the checklist items. It is initialized with the example list generated by `ListItem.generateExampleList()`.
///     - listName: String - The name of the checklist, which will be displayed as the navigation title. It is initialized with the value "Reminders 2".
/// - Examples:
///     ```swift
///     ContentView()
///     ```
struct ContentView: View {
    @State private var list = ListItem.generateExampleList()
    @State private var listName = "Reminders 2"
    
    var body: some View {
        CheckListView(list: list, name: listName)
    }
}

/// A `PreviewProvider` for the `ContentView`.
///
/// The `ContentView_Previews` is used to generate SwiftUI previews for the `ContentView`.
struct ContentView_Previews: PreviewProvider {
    
    static var previews: some View {
        ContentView()
    }
}
