//
//  CheckListCollectionViewModel.swift
//  AssignmentOne
//
//  Created by Steele Cooke on 5/4/2023.
//

/// The ViewModel for the associated view CheckListCollectionView.
///
/// `CheckListCollectionViewModel` is responsible for handling business logic for the it's associated view.
/// It initializes the `list` and `listName` states and passes them to the `CheckListView`.
/// - Variables:
///     - list: [ListItem] - An array of `ListItem` objects representing the checklist items. It is initialized with the example list generated by `ListItem.generateExampleList()`.
///     - listName: String - The name of the checklist, which will be displayed as the navigation title. It is initialized with the value "Reminders 2".
/// - Functions:
///     - removeCheckList - Removes a checklist from the list of checklists at a given offset.

import Foundation

class CheckListCollectionViewModel: ObservableObject {
    @Published var checkLists: [CheckList] = CheckList.generateExampleCheckLists()

    /// Removes a checklist from the list of checklists at a given offset.
    ///
    /// - Returns: No return.
    /// - Examples:
    ///     ```swift
    /// List {
    /// ForEach(viewModel.checkLists.indices, id: \.self) { index in
    ///     let list = viewModel.checkLists[index]
    /// }
    /// // The ForEach loop automatically passes the offset to the removeCheckList function.
    /// .onDelete(perform: viewModel.removeCheckList)
    ///     ```
    func removeCheckList(atOffsets offsets: IndexSet) {
        checkLists.remove(atOffsets: offsets)
    }
}
